#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get staged PHP files
STAGED_PHP_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')

if [ -z "$STAGED_PHP_FILES" ]; then
  exit 0
fi

# Run phpcbf on staged files
./vendor/bin/phpcbf --standard=phpcs.xml.dist $STAGED_PHP_FILES

# Add the fixed files to the commit
echo "$STAGED_PHP_FILES" | xargs git add 