on:
  pull_request:
    branches-ignore:
      # Do not run on auto submitted branches
      - '**-phpcbf'
      - 'dependabot/'
      - 'renovate/'
    paths:
      - '**.php'

name: PHP Lint

jobs:
  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      # Install dependencies and handle caching in one go.
      # @link https://github.com/marketplace/actions/install-composer-dependencies
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"

      - name: PHP Lint
        uses: overtrue/phplint@8.0
        with:
          path: .
