on:
    release:
        types: [published]

permissions:
    contents: write
    packages: write

name: Deploy to WordPress.org

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Get Version From Tag
              id: get_version
              uses: linchpin/action-get-latest-tag@v2.0.0
              with:
                  semver_only: true

            - name: Latest Version
              id: latest_version
              run: |
                  TAG=${{ steps.get_version.outputs.tag }}
                  echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT

            - name: Cache Composer dependencies
              uses: actions/cache@v4
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Composer Install
              uses: php-actions/composer@v6
              with:
                  dev: no
                  php_version: "8.2"
                  php_extensions: exif

            - name: Build Base Plugin Assets
              run: |
                  npm install && npm run build
                  rm -rf node_modules

            - name: Clean Build Files/Folders
              run: |
                  sed -i '/x-release-please-start-version/d' "./readme.txt"
                  sed -i '/x-release-please-end/d' "./readme.txt"
                  echo "✅ Removed release-please marker lines from readme.txt for .org distribution"

            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@54bd289b8525fd23a5c365ec369185f2966529c2 # v2.3.0
              with:
                  generate-zip: true
              env:
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SLUG: courier-notices

            - name: Upload release asset
              uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ steps.deploy.outputs.zip-path }}
                  asset_name: ${{ github.event.repository.name }}.zip
                  asset_content_type: application/zip
